#version 450

#extension GL_EXT_control_flow_attributes : require

const uint num_threads = 256;

layout(local_size_x = num_threads, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform parameter {
    uint ne;
    uint n_embd;
    uint hc;
    uint x_nb0;
    uint x_nb1;
    uint x_nb2;
    uint x_offset;
    uint weights_nb0;
    uint weights_nb1;
    uint weights_offset;
    uint dst_nb0;
    uint dst_nb1;
    uint dst_offset;
} p;

layout(binding = 0) readonly buffer XBuf { float data_x[]; };
layout(binding = 1) readonly buffer WeightsBuf { float data_weights[]; };
layout(binding = 2) writeonly buffer DstBuf { float data_dst[]; };

uint get_idx() {
    return gl_GlobalInvocationID.z * 262144 + gl_GlobalInvocationID.y * 512 + gl_GlobalInvocationID.x;
}

void main() {
    const uint idx = get_idx();
    if (idx >= p.ne) {
        return;
    }

    const uint i0 = idx % p.n_embd;
    const uint it = idx / p.n_embd;

    precise float sum = 0.0;
    for (uint ih = 0; ih < p.hc; ++ih) {
        const float xv = data_x[p.x_offset + i0*p.x_nb0 + ih*p.x_nb1 + it*p.x_nb2];
        const float wv = data_weights[p.weights_offset + ih*p.weights_nb0 + it*p.weights_nb1];
        sum = sum + xv * wv;
    }

    data_dst[p.dst_offset + i0*p.dst_nb0 + it*p.dst_nb1] = sum;
}
