#version 450

#include "generic_head.glsl"
#include "types.glsl"

#extension GL_EXT_control_flow_attributes : enable

layout(local_size_x = 512, local_size_y = 1, local_size_z = 1) in;

layout (binding = 0) readonly buffer G {A_TYPE data_g[];};
layout (binding = 1) readonly buffer X {B_TYPE data_x[];};
layout (binding = 2) writeonly buffer D {D_TYPE data_d[];};

void main() {
    const float GELU_COEF_A    = 0.044715f;
    const float SQRT_2_OVER_PI = 0.79788456080286535587989211986876f;
    const uint i = gl_GlobalInvocationID.z * 262144 + gl_GlobalInvocationID.y * 512 + gl_GlobalInvocationID.x;

    if (i >= p.KX) {
        return;
    }

    const float x = float(data_x[i]);
    const float t = tanh(SQRT_2_OVER_PI * x * (1.0f + GELU_COEF_A * x * x));
    const float dt = SQRT_2_OVER_PI * (1.0f + 3.0f * GELU_COEF_A * x * x) * (1.0f - t * t);
    data_d[i] = D_TYPE(float(data_g[i]) * 0.5f * (1.0f + t + x * dt));
}
