#version 450

#include "types.glsl"
#include "generic_binary_head.glsl"

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    const uint col = gl_GlobalInvocationID.x;

    if (col >= p.ne20) {
        return;
    }

    for (uint iz = gl_GlobalInvocationID.z; iz < p.ne22*p.ne23; iz += gl_NumWorkGroups.z) {
        const uint i3 = iz / p.ne22;
        const uint i2 = iz - i3*p.ne22;

        for (uint row = gl_GlobalInvocationID.y; row < p.ne21; row += gl_WorkGroupSize.y * gl_NumWorkGroups.y) {
            float sum = 0.0f;
            for (uint i = 0; i < p.ne10; ++i) {
                if (data_b[get_boffset() + i*p.nb10 + i2*p.nb11 + i3*p.nb12] == int(row)) {
                    sum += data_a[get_aoffset() + col*p.nb00 + i*p.nb01 + i2*p.nb02 + i3*p.nb03];
                }
            }

            data_d[get_doffset() + col*p.nb20 + row*p.nb21 + i2*p.nb22 + i3*p.nb23] = sum;
        }
    }
}
