#version 450

#include "types.glsl"

layout (push_constant) uniform parameter {
    uint ne;
    uint L;
    uint C;
    uint B;
    uint layout_id;
} p;

layout (binding = 0) readonly buffer X { float data_x[]; };
layout (binding = 1) readonly buffer B { float data_b[]; };
layout (binding = 2) writeonly buffer D { float data_d[]; };

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() {
    const uint idx = gl_GlobalInvocationID.z * 262144u + gl_GlobalInvocationID.y * 512u + gl_GlobalInvocationID.x;
    if (idx >= p.ne) {
        return;
    }
    const uint batch_stride = p.L * p.C;
    const uint batch = idx / batch_stride;
    if (batch >= p.B) {
        return;
    }
    const uint local_idx = idx - batch * batch_stride;
    const uint c = p.layout_id == 0u ? local_idx / p.L : local_idx % p.C;
    const uint x_idx = p.layout_id == 2u
        ? batch * batch_stride + (local_idx % p.C) * p.L + local_idx / p.C
        : idx;
    const float v = data_x[x_idx] + data_b[c];
    const float p_erf = 0.3275911f;
    const float a1_erf = 0.254829592f;
    const float a2_erf = -0.284496736f;
    const float a3_erf = 1.421413741f;
    const float a4_erf = -1.453152027f;
    const float a5_erf = 1.061405429f;
    const float z = v * 0.7071067811865475244f;
    const float sign_z = sign(z);
    const float az = abs(z);
    const float t = 1.0f / (1.0f + p_erf * az);
    const float y = 1.0f - (((((a5_erf * t + a4_erf) * t + a3_erf) * t + a2_erf) * t + a1_erf) * t) * exp(-az * az);
    data_d[idx] = 0.5f * v * (1.0f + sign_z * y);
}
