# Every kernel artifact is copied to a name carrying a hash of the design
# sources and the build-time knobs, and the backend looks only for that name.
# The hash covers what the artifacts are built from, not the interpreter that
# happened to run the build, so two interpreters over the same sources agree.
# A backend that moved on while the artifacts stayed behind - the ninja trap
# where the kernels target is not rebuilt - then fails with a clear message
# instead of driving an old design with a new stream, which reads as garbage
# model output and no error at all.
#
# The hash is also written to ../xdna-design-tag.h, which the backend
# #includes, so the two sides can only drift if one of them is rebuilt and the
# other is not - which is exactly the state the tagged name turns into a loud
# failure.

import hashlib
import os
import shutil

KERNEL_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(KERNEL_DIR, "..", "xdna-design-tag.h")

# The build-time environment knobs the designs read from outside. A change here
# is a change of design, exactly like a change of source.
#
# Only knobs that every stamping step sees belong here: the tag has to come out
# the same whether it is computed by a design as it builds or by the stamping
# step afterwards, or a build of one design would relabel the artifact of
# another and the backend would look for a name that does not exist. So this
# leaves out:
#   - knobs a design sets itself (POST_FILL_COL, POST_DRN_COL, ACT_RAW for the
#     merged layer): the source that sets them is hashed anyway, and the value
#     the stamping step would see is a different one;
#   - ACT_RAW for the standalone GEMV, which decides whether the prologue tile
#     is in that artifact: the two variants are separate files by construction
#     (fused_layer.xclbin and gemv_n32_r4_c8.xclbin), so it is not a knob of
#     either one's identity.
DESIGN_ENV = {
    "ATT_DEPTH",
    "CONV_DEPTH", "CONV_DIRECT", "CONV_GPO", "CONV_SLOT", "CONV_SPREAD",
    "GACT_COL", "GATED_ACT_SPLIT", "GATED_ATTN_ONCHIP", "GATED_AZ_COL",
    "GATED_DEPTH", "GATED_FMT", "GATED_HEADS", "GDN_STATE_STREAMS",
    "PKV_ONCHIP",
}


def tag(extra: str = "") -> str:
    src = []
    for f in sorted(os.listdir(KERNEL_DIR)):
        if not f.endswith(".py") or f == "design_tag.py":
            continue
        with open(os.path.join(KERNEL_DIR, f), "rb") as fh:
            src.append(f + "\0" + fh.read().decode(errors="replace"))
    env = "".join(f"{k}={os.environ[k]}\n"
                  for k in sorted(DESIGN_ENV) if k in os.environ)
    blob = "\0".join(src) + "\1" + env + "\2" + extra
    return hashlib.sha256(blob.encode()).hexdigest()[:12]


def _write_header(t: str) -> None:
    header = f"#pragma once\n// Generated by kernels/design_tag.py.\n" \
             f"#define XDNA_DESIGN_TAG \"{t}\"\n"
    try:
        with open(HEADER, "r") as fh:
            current = fh.read()
    except OSError:
        current = None
    if current != header:
        # Written only when it changed, so a rebuild with an unchanged design
        # does not retouch the header and does not recompile the backend.
        with open(HEADER, "w") as fh:
            fh.write(header)
        print(f"design tag {t} (new)")


# The stems the backend loads under tagged names: the merged recurrent-layer
# design and the decode GEMV, one per array split. The prefill artifacts (GEMM,
# conv, flash attention) are loaded by geometry-encoded names and stay untagged.
KNOWN_STEMS = [
    "fused_layer", "gemv_n32_r4_c8",
]


# <stem>.xclbin -> <stem>_<tag>.xclbin, <stem>.insts.bin ->
# <stem>_<tag>.insts.bin: the names the backend looks for, which are not what
# splitext gives for the two-suffix instruction file.
def _tagged(src: str, t: str) -> str:
    d, name = os.path.split(src)
    for suffix in (".insts.bin", ".xclbin"):
        if name.endswith(suffix):
            return os.path.join(d, f"{name[:-len(suffix)]}_{t}{suffix}")
    stem, ext = os.path.splitext(name)
    return os.path.join(d, f"{stem}_{t}{ext}")


def stamp(xclbin_path, insts_path=None, extra: str = ""):
    """Copy the artifact under its tagged name and refresh the tag header."""
    t = tag(extra)
    _write_header(t)
    for src in (xclbin_path, insts_path):
        src = str(src) if src is not None else None
        if src and os.path.exists(src):
            shutil.copy2(src, _tagged(src, t))


def stamp_all(bindir: str, extra: str = "") -> None:
    """Tagged copies for every stem the backend loads, after any design
    rebuilt. The tag covers all the design sources, so one design changing
    moves the tag for all of them, and the designs ninja did not rebuild have
    no stamp of their own to run."""
    t = tag(extra)
    _write_header(t)
    for stem in KNOWN_STEMS:
        for ext in (".xclbin", ".insts.bin"):
            src = os.path.join(bindir, stem + ext)
            if os.path.exists(src):
                shutil.copy2(src, _tagged(src, t))
    print(f"design tag {t} (stamp-all)")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(prog="design_tag")
    ap.add_argument("--stamp-dir", default=None)
    ap.add_argument("--extra", default="")
    opts = ap.parse_args()
    if opts.stamp_dir:
        stamp_all(opts.stamp_dir, opts.extra)
    else:
        print(tag(opts.extra))
