# Every kernel artifact is copied to a name carrying a hash of the design
# sources and the build-time knobs, and the backend looks only for that name.
# The hash covers what the artifacts are built from, not the interpreter that
# happened to run the build, so two interpreters over the same sources agree.
# A backend that moved on while the artifacts stayed behind - the ninja trap
# where the kernels target is not rebuilt - then fails with a clear message
# instead of driving an old design with a new stream, which reads as garbage
# model output and no error at all.
#
# The hash is also written to xdna-design-tag.h and passed to the backend as a
# compile definition, so the two sides can only drift if one of them is rebuilt
# and the other is not - which is exactly the state the tagged name turns into a
# loud failure. The build passes --header so that the file lands in the build
# tree; the default keeps a standalone run writing next to the sources.

import glob
import hashlib
import os
import shutil

KERNEL_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(KERNEL_DIR, "..", "xdna-design-tag.h")

# The build-time environment knobs the designs read from outside. A change here
# is a change of design, exactly like a change of source.
#
# Only knobs that every stamping step sees belong here: the tag has to come out
# the same whether it is computed by a design as it builds or by the stamping
# step afterwards, or a build of one design would relabel the artifact of
# another and the backend would look for a name that does not exist. So this
# leaves out:
#   - knobs a design sets itself (POST_FILL_COL, POST_DRN_COL, ACT_RAW for the
#     merged layer): the source that sets them is hashed anyway, and the value
#     the stamping step would see is a different one;
#   - ACT_RAW for the standalone GEMV, which decides whether the prologue tile
#     is in that artifact: the two variants are separate files by construction
#     (fused_layer.xclbin and gemv_n32_r4_c8.xclbin), so it is not a knob of
#     either one's identity.
DESIGN_ENV = {
    "ATT_DEPTH",
    "CONV_DEPTH", "CONV_DIRECT", "CONV_GPO", "CONV_SLOT", "CONV_SPREAD",
    "GACT_COL", "GATED_ACT_SPLIT", "GATED_ATTN_ONCHIP", "GATED_AZ_COL",
    "GATED_DEPTH", "GATED_FMT", "GATED_HEADS", "GDN_STATE_STREAMS",
    "PKV_ONCHIP",
}


def tag(extra: str = "") -> str:
    # Every source that goes into an artifact: the generators, the C/C++ they
    # compile, and the shared headers. design_tag.py is excluded so the tag can
    # not depend on the hash of the code computing it.
    src = []
    for f in sorted(os.listdir(KERNEL_DIR)):
        if f == "design_tag.py" or not f.endswith((".py", ".h", ".cc")):
            continue
        with open(os.path.join(KERNEL_DIR, f), "rb") as fh:
            src.append(f + "\0" + fh.read().decode(errors="replace"))
    env = "".join(f"{k}={os.environ[k]}\n"
                  for k in sorted(DESIGN_ENV) if k in os.environ)
    blob = "\0".join(src) + "\1" + env + "\2" + extra
    return hashlib.sha256(blob.encode()).hexdigest()[:12]


def _write_header(t: str, path: str = HEADER) -> None:
    header = f"#pragma once\n// Generated by kernels/design_tag.py.\n" \
             f"#define XDNA_DESIGN_TAG \"{t}\"\n"
    try:
        with open(path, "r") as fh:
            current = fh.read()
    except OSError:
        current = None
    if current != header:
        # Written only when it changed, so a rebuild with an unchanged design
        # does not retouch the header and does not recompile the backend.
        with open(path, "w") as fh:
            fh.write(header)
        print(f"design tag {t} (new)")


# The stems the backend loads under tagged names: the merged recurrent-layer
# design and the decode GEMV, one per array split. The prefill artifacts (GEMM,
# conv, flash attention) are loaded by geometry-encoded names and stay untagged.
KNOWN_STEMS = [
    "fused_layer", "gemv_n32_r4_c8",
]


# <stem>.xclbin -> <stem>_<tag>.xclbin, <stem>.insts.bin ->
# <stem>_<tag>.insts.bin: the names the backend looks for, which are not what
# splitext gives for the two-suffix instruction file.
def _tagged(src: str, t: str) -> str:
    d, name = os.path.split(src)
    for suffix in (".insts.bin", ".xclbin"):
        if name.endswith(suffix):
            return os.path.join(d, f"{name[:-len(suffix)]}_{t}{suffix}")
    stem, ext = os.path.splitext(name)
    return os.path.join(d, f"{stem}_{t}{ext}")


def _tag_copy(src: str, t: str) -> None:
    """Copy an artifact to its tagged name, without the source's timestamp.

    Deliberately not copy2: the tagged file is one output of a rule whose other
    inputs are the design artifacts, so a preserved source timestamp can leave
    it older than an input, and ninja reruns the stamping step every build.
    """
    shutil.copyfile(src, _tagged(src, t))


def stamp(xclbin_path, insts_path=None, extra: str = ""):
    """Copy the artifact under its tagged name.

    The tag header is refreshed by the build's own stamping step (stamp_all,
    run from the kernel rule), never from here: a standalone compile has none
    of the build's knobs in its environment, so writing it would relabel the
    build tree with a tag the backend then binds against other artifacts.
    """
    files = [str(p) for p in (xclbin_path, insts_path) if p and os.path.exists(str(p))]
    if not files:
        return
    t = tag(extra)
    for src in files:
        _tag_copy(src, t)


def _prune_stale(bindir: str, keep: str) -> int:
    """Drop tagged copies of an older design. Only the current tag is ever
    loaded, so every other one is dead weight that also hides which artifact is
    live - after enough tag changes the directory is a pile of them."""
    removed = 0
    for stem in KNOWN_STEMS:
        for ext in (".xclbin", ".insts.bin"):
            for path in glob.glob(os.path.join(bindir, f"{stem}_*{ext}")):
                mid = os.path.basename(path)[len(stem) + 1 : -len(ext)]
                if len(mid) == 12 and mid != keep and all(c in "0123456789abcdef" for c in mid):
                    os.remove(path)
                    removed += 1
    return removed


def stamp_all(bindir: str, extra: str = "", header: str = HEADER) -> None:
    """Tagged copies for every stem the backend loads, after any design
    rebuilt. The tag covers all the design sources, so one design changing
    moves the tag for all of them, and the designs ninja did not rebuild have
    no stamp of their own to run."""
    t = tag(extra)
    _write_header(t, header)
    for stem in KNOWN_STEMS:
        for ext in (".xclbin", ".insts.bin"):
            src = os.path.join(bindir, stem + ext)
            if os.path.exists(src):
                _tag_copy(src, t)
    stale = _prune_stale(bindir, t)
    print(f"design tag {t} (stamp-all)" + (f", {stale} stale artifact(s) removed" if stale else ""))


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(prog="design_tag")
    ap.add_argument("--stamp-dir", default=None)
    ap.add_argument("--header", default=HEADER,
                    help="where the tag header is written with --stamp-dir (default: next to the sources)")
    ap.add_argument("--extra", default="")
    opts = ap.parse_args()
    if opts.stamp_dir:
        stamp_all(opts.stamp_dir, opts.extra, opts.header)
    else:
        print(tag(opts.extra))
