# Every kernel artifact is copied to a name carrying a hash of the design
# sources and the build-time knobs, and the backend looks only for that name.
# The hash covers what the artifacts are built from, not the interpreter that
# happened to run the build, so two interpreters over the same sources agree.
# A backend that moved on while the artifacts stayed behind - the ninja trap
# where the kernels target is not rebuilt - then fails with a clear message
# instead of driving an old design with a new stream, which reads as garbage
# model output and no error at all.
#
# The hash is also written to ../xdna-design-tag.h, which the backend
# #includes, so the two sides can only drift if one of them is rebuilt and the
# other is not - which is exactly the state the tagged name turns into a loud
# failure.

import hashlib
import os
import shutil

KERNEL_DIR = os.path.dirname(os.path.abspath(__file__))
HEADER = os.path.join(KERNEL_DIR, "..", "xdna-design-tag.h")

# The build-time environment knobs a design reads. A change here is a change
# of design, exactly like a change of source.
DESIGN_ENV = {
    "ATT_DEPTH", "CONV_GPO", "CONV_SLOT", "CONV_SPREAD",
    "GATED_ACT_SPLIT", "GATED_ATTN_ONCHIP", "GATED_DEPTH", "GATED_HEADS",
    "GATED_FMT", "GDN_STATE_STREAMS",
    "GEMV_STACK", "GEMV_VEC", "GEMV_W_DEPTH",
    "PKV_ONCHIP",
}


def tag(extra: str = "") -> str:
    src = []
    for f in sorted(os.listdir(KERNEL_DIR)):
        if not f.endswith(".py") or f == "design_tag.py":
            continue
        with open(os.path.join(KERNEL_DIR, f), "rb") as fh:
            src.append(f + "\0" + fh.read().decode(errors="replace"))
    env = "".join(f"{k}={os.environ[k]}\n"
                  for k in sorted(DESIGN_ENV) if k in os.environ)
    blob = "\0".join(src) + "\1" + env + "\2" + extra
    return hashlib.sha256(blob.encode()).hexdigest()[:12]


def _write_header(t: str) -> None:
    header = f"#pragma once\n// Generated by kernels/design_tag.py.\n" \
             f"#define XDNA_DESIGN_TAG \"{t}\"\n"
    try:
        with open(HEADER, "r") as fh:
            current = fh.read()
    except OSError:
        current = None
    if current != header:
        # Written only when it changed, so a rebuild with an unchanged design
        # does not retouch the header and does not recompile the backend.
        with open(HEADER, "w") as fh:
            fh.write(header)
        print(f"design tag {t} (new)")


# The stems the backend loads under tagged names: the merged recurrent-layer
# design and the decode GEMV, one per array split. The prefill artifacts (GEMM,
# conv, flash attention) are loaded by geometry-encoded names and stay untagged.
KNOWN_STEMS = [
    "fused_layer", "gemv_n32_r4_c8", "gemv_n128_r1_c8",
]


def stamp(xclbin_path, insts_path=None, extra: str = ""):
    """Copy the artifact under its tagged name and refresh the tag header."""
    t = tag(extra)
    _write_header(t)
    for src in (xclbin_path, insts_path):
        src = str(src) if src is not None else None
        if src and os.path.exists(src):
            base, ext = os.path.splitext(src)
            shutil.copy2(src, f"{base}_{t}{ext}")


def stamp_all(bindir: str, extra: str = "") -> None:
    """Tagged copies for every stem the backend loads, after any design
    rebuilt. The tag covers all the design sources, so one design changing
    moves the tag for all of them, and the designs ninja did not rebuild have
    no stamp of their own to run."""
    t = tag(extra)
    _write_header(t)
    for stem in KNOWN_STEMS:
        for ext in (".xclbin", ".insts.bin"):
            src = os.path.join(bindir, stem + ext)
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(bindir, stem + f"_{t}" + ext))
    print(f"design tag {t} (stamp-all)")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(prog="design_tag")
    ap.add_argument("--stamp-dir", default=None)
    ap.add_argument("--extra", default="")
    opts = ap.parse_args()
    if opts.stamp_dir:
        stamp_all(opts.stamp_dir, opts.extra)
    else:
        print(tag(opts.extra))
