/*!
 * turbo-quant/copy_to_quant.glsl - do not use directly, included by ../copy_to_quant.glsl
 */

#if defined(DATA_A_ANY_TBQ3_OR_PQ3_0) || defined(DATA_A_ANY_TBQ4_OR_PQ4_0)
// Cooperative quantization path for TurboQuant / PolarQuant types: one workgroup
// (WG == 32 threads) handles a single block of QUANT_K values, using subgroupAdd
// for the norm / correction reductions, a parallel Fast Hadamard Transform, and
// either subgroupBallot (when gl_SubgroupSize == WG) or a shared-memory atomicOr
// fallback for the QJL sign sketch.
//
// Subgroup size generalization: the workgroup is always 32 threads, but the
// hardware subgroup size can be smaller (Intel Xe/Arc: 8 or 16; Mali/Adreno: 4,
// 8, 16; AMD wave32: 32; NVIDIA/Apple: 32; AMD wave64 with WG=32: 32 active
// lanes in a 64-lane wave). We specialize on `SG_SIZE` at pipeline creation and
// derive `NSG = WG / SG_SIZE` (number of subgroups per workgroup). When NSG==1,
// the specialized SPIR-V emits the same subgroup ops (subgroupAdd and
// subgroupBallot) and the same memory accesses as the original single-subgroup
// shader, with the shared-memory stitch path dead-code-eliminated; when NSG>1,
// the reductions and the QJL bit-pack go through a shared-memory stitching
// step. SG_SIZE defaults to 32, so hosts that don't set the spec constant get
// the original behaviour.
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_ballot : enable

// Subgroup size the pipeline will actually run with. The host passes this via
// VkPipelineShaderStageRequiredSubgroupSizeCreateInfoEXT and sets the spec
// constant to the matching value. Default 32 matches the original shader.
// NOTE: constant_id 0 is already used by generic_binary_head.glsl (norepeat)
// in the SET_ROWS path; we pick 1 so the SET_ROWS entrypoint can set both
// norepeat (id 0) and SG_SIZE (id 1) without collision. For the plain CPY
// path generic_unary_head.glsl declares no spec constants, and unused entries
// in VkSpecializationInfo are silently ignored by the driver, so passing a
// 2-element {unused, SG_SIZE} vector from the host is safe in both cases.
layout(constant_id = 1) const uint SG_SIZE = 32u;

// Workgroup is always 32 threads for the cooperative TBQ/PQ path, see the
// layout(local_size_x = 32) in ../copy_to_quant.glsl. NSG is how many subgroups
// cover the WG.

#include "../tq_utils.glsl"

#define TBQ_COOP 1
#define TBQ_WG 32u
// Scratch for the cross-subgroup reduction stitch. Sized for the smallest
// plausible subgroup (SG_SIZE=4 -> NSG=8). When SG_SIZE==32, NSG==1 and this
// array is dead-code-eliminated after spec-constant substitution.
shared float tq_sh_red[TBQ_WG / 4u];
// Scratch for the QJL ballot stitch: one uint per 32 bits of QJL output.
// Longest QJL is BK=128 -> 128/8 = 16 bytes = 4 uints; we allocate the max.
shared uint tq_sh_qjl[4];

// Cooperative scratch: one workgroup == one block.
shared float tbq_sh_x[QUANT_K];
shared uint tbq_sh_idx[QUANT_K];
#if defined(DATA_A_ANY_TBQ3_OR_4_0)
shared float tbq_sh_proj[QUANT_K];
#endif

#if defined(DATA_A_ANY_TBQ3_OR_PQ3_0)
// Decision boundaries (midpoints between adjacent codebook centroids). The d=64
// and d=128 Lloyd-Max codebooks have different spreads (sigma ~= 1/sqrt(d) is
// larger at d=64), so their boundaries differ. TQ_D64 is defined by tq_utils.comp
// when any `_64` DATA_* macro is set.
#if defined(TQ_D64)
// Midpoints of TQ3_CODEBOOK_64 (must track TBQ3_CB in tq_utils.comp).
// Generated by scripts/compute_tq_codebooks.py --dims 64 --bits 3 --c-code.
const float TBQ3_B[7] = float[7](
    -0.21504089488485487, -0.13000006107175099, -0.06215072107474821,
     0.0,
     0.06215072107474821,  0.13000006107175099,  0.21504089488485487
);
#else
// Midpoints of TQ3_CODEBOOK_128.
// Generated by scripts/compute_tq_codebooks.py --dims 128 --bits 3 --c-code.
const float TBQ3_B[7] = float[7](
    -0.15326847648335928, -0.09236268752201893, -0.04409495934473917,
     0.0,
     0.04409495934473917,  0.09236268752201893,  0.15326847648335928
);
#endif
uint tbq_quantize_val(float val) {
    if (val < TBQ3_B[3]) {
        if (val < TBQ3_B[1]) { return val < TBQ3_B[0] ? 0u : 1u; }
        else                 { return val < TBQ3_B[2] ? 2u : 3u; }
    } else {
        if (val < TBQ3_B[5]) { return val < TBQ3_B[4] ? 4u : 5u; }
        else                 { return val < TBQ3_B[6] ? 6u : 7u; }
    }
}
#endif

#if defined(DATA_A_ANY_TBQ4_OR_PQ4_0)
// See comment on TBQ3_B above.
#if defined(TQ_D64)
// Midpoints of TQ4_CODEBOOK_64 (must track TBQ4_CB in tq_utils.comp).
// Generated by scripts/compute_tq_codebooks.py --dims 64 --bits 4 --c-code.
const float TBQ4_B[15] = float[15](
    -0.29180268220177841, -0.22582717916950065, -0.17683323251927041,
    -0.13565345351930996, -0.09885566129814261, -0.06466967310003119,
    -0.03198822095395431,  0.0,
     0.03198822095395431,  0.06466967310003119,  0.09885566129814261,
     0.13565345351930996,  0.17683323251927041,  0.22582717916950065,
     0.29180268220177841
);
#else
// Midpoints of TQ4_CODEBOOK_128.
// Generated by scripts/compute_tq_codebooks.py --dims 128 --bits 4 --c-code.
const float TBQ4_B[15] = float[15](
    -0.20921017409079767, -0.16127738300848593, -0.12600405430352871,
    -0.09651953803632701, -0.07026832190197044, -0.04593911875417284,
    -0.02271517840509901,  0.0,
     0.02271517840509901,  0.04593911875417284,  0.07026832190197044,
     0.09651953803632701,  0.12600405430352871,  0.16127738300848593,
     0.20921017409079767
);
#endif
uint tbq_quantize_val(float val) {
    if (val < TBQ4_B[7]) {
        if (val < TBQ4_B[3]) {
            if (val < TBQ4_B[1])  { return val < TBQ4_B[0] ? 0u : 1u; }
            else                  { return val < TBQ4_B[2] ? 2u : 3u; }
        } else {
            if (val < TBQ4_B[5])  { return val < TBQ4_B[4] ? 4u : 5u; }
            else                  { return val < TBQ4_B[6] ? 6u : 7u; }
        }
    } else {
        if (val < TBQ4_B[11]) {
            if (val < TBQ4_B[9])  { return val < TBQ4_B[8]  ? 8u  : 9u;  }
            else                  { return val < TBQ4_B[10] ? 10u : 11u; }
        } else {
            if (val < TBQ4_B[13]) { return val < TBQ4_B[12] ? 12u : 13u; }
            else                  { return val < TBQ4_B[14] ? 14u : 15u; }
        }
    }
}
#endif

// Workgroup-wide sum. At NSG==1 (SG_SIZE >= TBQ_WG, i.e. the whole workgroup
// fits in one subgroup) this is a single subgroupAdd, matching the original
// code exactly -- the trailing shared-memory stitch dead-code-folds away when
// the spec constant `SG_SIZE` resolves to >= TBQ_WG. SG_SIZE > TBQ_WG happens on
// AMD wave64 when the host doesn't request a 32-lane subgroup; subgroupAdd
// still returns the correct sum since the extra lanes are inactive and
// contribute zero.
float tq_wg_add(float x) {
    // Use max(SG_SIZE, TBQ_WG) so SG_SIZE > TBQ_WG behaves like SG_SIZE == TBQ_WG
    // (NSG = 1). Any SG_SIZE >= TBQ_WG fits the workgroup in one subgroup.
    const uint SG = SG_SIZE < TBQ_WG ? SG_SIZE : TBQ_WG;
    const uint NSG = TBQ_WG / SG;
    float s = subgroupAdd(x);
    if (NSG == 1u) {
        return s;
    }
    if (subgroupElect()) {
        tq_sh_red[gl_SubgroupID] = s;
    }
    barrier();
    float total = 0.0;
    [[unroll]] for (uint i = 0u; i < NSG; i++) {
        total += tq_sh_red[i];
    }
    return total;
}

void quantize(uint dst_idx, uint src_idx)
{
#if defined(DATA_A_ANY_TBQ3_OR_PQ3_0)
    #define TBQ_CODEBOOK TBQ3_CB
#elif defined(DATA_A_ANY_TBQ4_OR_PQ4_0)
    #define TBQ_CODEBOOK TBQ4_CB
#endif

  const uint BK = QUANT_K;
  const uint QS_BYTES =
#if defined(DATA_A_ANY_TBQ3_OR_PQ3_0)
      (BK * 3u + 7u) / 8u;
#elif defined(DATA_A_ANY_TBQ4_OR_PQ4_0)
      BK / 2u;
#endif
    const uint WG = 32u;
    const uint STRIDE = BK / WG;
    const uint lid = gl_LocalInvocationID.x;

    // Load input, compute squared norm (strided indexing for coalesced reads).
    float local_sq = 0.0;
    [[unroll]] for (uint s = 0u; s < STRIDE; s++) {
        uint j = lid + s * WG;
        float v = data_s[src_idx + j];
        tbq_sh_x[j] = v;
        local_sq += v * v;
    }
    float total_sq = tq_wg_add(local_sq);
    float norm = sqrt(total_sq);

    if (lid == 0u) {
        data_q[dst_idx].d = float16_t(norm);
    }

    // Uniform flag: all threads must agree on whether the norm is effectively zero.
    // Using subgroupBroadcast ensures uniformity and avoids divergent barriers.
    bool skip_quant = subgroupBroadcast(norm < 1e-15, 0u);

    if (skip_quant) {
        for (uint j = lid; j < QS_BYTES; j += WG) data_q[dst_idx].qs[j] = uint8_t(0);
#if defined(DATA_A_ANY_TBQ3_OR_4_0)
        const uint QJL_BYTES = BK / 8u;
        for (uint j = lid; j < QJL_BYTES; j += WG) data_q[dst_idx].qjl[j] = uint8_t(0);
        if (lid == 0u) data_q[dst_idx].d_r = float16_t(0.0);
#endif
    } else {
        float inv_norm = 1.0 / norm;

        // Quantize each value; strided write into shared idx table.
        [[unroll]] for (uint s = 0u; s < STRIDE; s++) {
            uint j = lid + s * WG;
            tbq_sh_idx[j] = tbq_quantize_val(tbq_sh_x[j] * inv_norm);
        }
        barrier();

#if defined(DATA_A_ANY_TBQ3_OR_PQ3_0)
        const uint NUM_GROUPS = BK / 8u;
        // Pack 8 indices -> 3 bytes per group. NUM_GROUPS is 16 (BK=128) or 8 (BK=64),
        // so one thread per group covers all groups.
        if (lid < NUM_GROUPS) {
            uint g = lid;
            uint accum = 0u;
            [[unroll]] for (uint i = 0u; i < 8u; i++) {
                accum |= tbq_sh_idx[g * 8u + i] << (i * 3u);
            }
            uint base = g * 3u;
            data_q[dst_idx].qs[base + 0u] = uint8_t(accum & 0xFFu);
            data_q[dst_idx].qs[base + 1u] = uint8_t((accum >> 8u) & 0xFFu);
            data_q[dst_idx].qs[base + 2u] = uint8_t((accum >> 16u) & 0xFFu);
        }
#elif defined(DATA_A_ANY_TBQ4_OR_PQ4_0)
        // Pack nibble pairs: QS_BYTES = BK/2 (64 for BK=128, 32 for BK=64).
        for (uint b = lid; b < QS_BYTES; b += WG) {
          uint i0 = tbq_sh_idx[2u * b];
          uint i1 = tbq_sh_idx[2u * b + 1u];
          data_q[dst_idx].qs[b] = uint8_t(i0 | (i1 << 4u));
        }
#endif
    }

    // Only run norm correction and QJL if quantization was performed.
    if (skip_quant)
        return;
#if defined(TQ_NORM_CORRECTION)
    float local_xc = 0.0;
    float local_cc = 0.0;
    [[unroll]] for (uint s = 0u; s < STRIDE; s++) {
        uint j = lid + s * WG;
        float cv = TBQ_CODEBOOK[tbq_sh_idx[j]];
        local_xc += tbq_sh_x[j] * cv;
        local_cc += cv * cv;
    }
    float dot_xc = tq_wg_add(local_xc);
    float dot_cc = tq_wg_add(local_cc);
    if (dot_cc > 1e-15) {
        norm = dot_xc / dot_cc;
    }
    if (lid == 0u) data_q[dst_idx].d = float16_t(norm);
#endif

#if defined(DATA_A_ANY_TBQ3_0) || defined(DATA_A_ANY_TBQ4_0)
    const uint QJL_BYTES = BK / 8u;

    // Residual with pre-applied QJL sign diagonal for the upcoming FHT.
    float local_rsq = 0.0;
    [[unroll]] for (uint s = 0u; s < STRIDE; s++) {
        uint j = lid + s * WG;
        float r = tbq_sh_x[j] - TBQ_CODEBOOK[tbq_sh_idx[j]] * norm;
        tbq_sh_proj[j] = r * qjl_get_sign(j);
        local_rsq += r * r;
    }
    float r_norm = sqrt(tq_wg_add(local_rsq));
    if (lid == 0u) data_q[dst_idx].d_r = float16_t(r_norm);

    // Uniform flag: all threads must agree on whether to run the FHT/QJL path.
    // Using a workgroup reduction ensures uniformity and avoids divergent barriers.
    bool skip_fht = subgroupBroadcast(r_norm < 1e-15, 0u);

    if (skip_fht) {
        for (uint j = lid; j < QJL_BYTES; j += WG) data_q[dst_idx].qjl[j] = uint8_t(0);
    } else {
        // Parallel in-place FHT: each pass has BK/2 independent butterflies distributed
        // across the 32 threads.
        for (uint h = 1u; h < BK; h <<= 1u) {
            for (uint bi = lid; bi < BK / 2u; bi += WG) {
                uint grp = bi / h;
                uint pos = bi % h;
                uint j = grp * (h << 1u) + pos;
                float a = tbq_sh_proj[j];
                float b = tbq_sh_proj[j + h];
                tbq_sh_proj[j]     = a + b;
                tbq_sh_proj[j + h] = a - b;
            }
            barrier();
        }

        // Pack QJL sign bits into qjl[]. We stage into tq_sh_qjl[] (one uint per
        // 32 sign bits) and then have lanes 0..QJL_WORDS-1 each emit one 32-bit
        // word as four uint8_t SSBO stores. This pattern spreads byte writes
        // across QJL_WORDS lanes and matches the working stitch path; an earlier
        // SG_SIZE >= TBQ_WG variant that had lid==0 alone emit all 16 bytes of
        // qjl across an [[unroll]] STRIDE loop hung the NVIDIA 595 driver on
        // RTX 5090 (NV_coopmat2), so this single path is used unconditionally.
        const uint QJL_WORDS = (QJL_BYTES + 3u) / 4u;
        if (lid < QJL_WORDS) tq_sh_qjl[lid] = 0u;
        barrier();
        if (SG_SIZE >= TBQ_WG) {
            // Single subgroup covers the workgroup: subgroupBallot.x is the
            // 32-bit sign mask for one BK/SG chunk. subgroupElect() picks one
            // lane to deposit each word into shared.
            [[unroll]] for (uint s = 0u; s < STRIDE; s++) {
                uint j = lid + s * WG;
                uvec4 ballot = subgroupBallot(tbq_sh_proj[j] > 0.0);
                if (subgroupElect()) {
                    tq_sh_qjl[s] = ballot.x;
                }
            }
        } else {
            // Smaller subgroups: each ballot only spans SG_SIZE lanes, so fall
            // back to atomicOr in shared memory.
            [[unroll]] for (uint s = 0u; s < STRIDE; s++) {
                uint j = lid + s * WG;
                if (tbq_sh_proj[j] > 0.0) {
                    atomicOr(tq_sh_qjl[j / 32u], 1u << (j % 32u));
                }
            }
        }
        barrier();
        if (lid < QJL_WORDS) {
            uint bits = tq_sh_qjl[lid];
            uint byte_off = lid * 4u;
            data_q[dst_idx].qjl[byte_off + 0u] = uint8_t(bits & 0xFFu);
            data_q[dst_idx].qjl[byte_off + 1u] = uint8_t((bits >> 8u) & 0xFFu);
            data_q[dst_idx].qjl[byte_off + 2u] = uint8_t((bits >> 16u) & 0xFFu);
            data_q[dst_idx].qjl[byte_off + 3u] = uint8_t((bits >> 24u) & 0xFFu);
        }
    }
#endif
#undef TBQ_CODEBOOK
}
#undef TBQ_WG
#endif
